environment:
 myget_nuget_password:
  secure: mn5+CQ4OEuwGskUxOKqLOtIkTmbUqk7vMfoWxDwxp8c=
image: Visual Studio 2017
before_build:
 - nuget restore "RES.Configuration.sln" -verbosity quiet
 - nuget sources add -Name "myget" -Source "https://www.myget.org/F/res/api/v2/package" -username "res" -password "%myget_nuget_password%"
after_build:
 #- nuget pack RES.Configuration\RES.Configuration.csproj -prop Configuration=Release -Build -Symbols
 - msbuild RES.Configuration\RES.Configuration.csproj /t:pack
 - nuget push *.nupkg -source myget 
 #-UserName res -Password %myget_nuget_password% 
artifacts:
 - path: artifacts.zip
notifications:
  - provider: Email
    to:
      - cedd.burge@res-group.com
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
