environment:
  myget_api_key:
    secure: lgOtQrScOwS6TFok8/s8y0FyvqYSWV3tnjWQqE0IEq1GmSsJUNNDVfCqpTFzT8e4
image: Visual Studio 2017
before_build:
 - nuget restore "RES.Configuration.sln" -verbosity quiet
 #- nuget sources add -Name "myget" -Source "https://www.myget.org/F/res/api/v2/package" -username "res" -password "%myget_nuget_password%"
after_build:
 #- nuget pack RES.Configuration\RES.Configuration.csproj -prop Configuration=Release -Build -Symbols
 - msbuild RES.Configuration\RES.Configuration.csproj /t:pack
 - nuget push BuiltDLLs\Debug\*.nupkg -Source "https://www.myget.org/F/res/api/v2/package" -ApiKey %myget_api_key%
artifacts:
 - path: artifacts.zip
notifications:
  - provider: Email
    to:
      - cedd.burge@res-group.com
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
