environment:
  myget_api_key:
    secure: lgOtQrScOwS6TFok8/s8y0FyvqYSWV3tnjWQqE0IEq1GmSsJUNNDVfCqpTFzT8e4
image: Visual Studio 2017
build_script:
 - nuget restore "RES.Configuration.sln" -verbosity quiet
 - msbuild RES.Configuration\RES.Configuration.csproj /t:pack /p:IncludeSymbols=true
artifacts:
 - path: BuiltDLLs\Debug\*.nupkg 
notifications:
  - provider: Email
    to:
      - cedd.burge@res-group.com
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
